version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: webhook_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: webhook_pipeline
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webhook_user -d webhook_pipeline"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: webhook_user
      RABBITMQ_DEFAULT_PASS: webhook_pass
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  worker-main:
    build: .
    command: node dist/worker/worker.js
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - WORKER_TYPE=main
    env_file:
      - .env

  worker-retry:
    build: .
    command: node dist/worker/worker.js
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - WORKER_TYPE=retry
    env_file:
      - .env

volumes:
  pgdata:
  rabbitmqdata: